name: Go
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  go-tests:
    name: "test: ${{ matrix.os }}/go-${{ matrix.golang }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        golang: ["1.20.x", "1.21.x"]
        os: ["windows-latest", "macos-latest", "ubuntu-latest"]
    env:
      OS: ${{ matrix.os }}
      GOLANG: ${{ matrix.golang }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.golang }}
      - name: Check go.mod and go.sum
        run: |
          go mod tidy -v
          git --no-pager diff go.mod go.sum
          git --no-pager diff --quiet go.mod go.sum
      - name: Run tests
        run: go test -v -count=5 ./...
